/*
 * Copyright (C) 2015 Steven Rod.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package view;

import subView.NewCodigo;
import subView.SelectUnidad;
import control.ProductosController;
import java.awt.Frame;
import javax.swing.JOptionPane;
import model.ModelProductos;


/**
 *
 * @author Steven
 */
public class AddProduct extends javax.swing.JDialog {

    
     ProductosController controlProduct; // Controlador de Productos
     private boolean panel = false; // Variable ( Muestra Mas Campos)
     Hogarcito parent;
     int type;
     
    /**
     * Creates new form AddProduct
     */
    
    /**
     * Creates new form AddProduct
     * @param parent
     * @param modal
     */
    public AddProduct(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       // jPanel2.setVisible(false);
        this.parent = (Hogarcito)parent;
       
    }
    
    public AddProduct(java.awt.Frame parent, boolean modal,ProductosController pC,int typeP) {
        super(parent, modal);
        initComponents();
      //  jPanel2.setVisible(false);
        controlProduct = pC;
        this.parent = (Hogarcito)parent;
        this.type = typeP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        spinCantidad = new javax.swing.JSpinner();
        txtUnidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("<Nombre Producto>");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 281, -1));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigo.setText(" <Codigo Producto>");
        txtCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoMouseClicked(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, -1));

        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        txtDescripcion.setText("<Descripcion>");
        txtDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescripcionMouseClicked(evt);
            }
        });
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 260, -1));

        spinCantidad.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        getContentPane().add(spinCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 170, 60));

        txtUnidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUnidad.setForeground(new java.awt.Color(153, 153, 153));
        txtUnidad.setText("<Unidad Medida>");
        txtUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUnidadMouseClicked(evt);
            }
        });
        getContentPane().add(txtUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 281, -1));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 170, 100));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 90, 70));

        labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new_products.jpg"))); // NOI18N
        getContentPane().add(labelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUnidadMouseClicked
       SelectUnidad sU = new SelectUnidad(this, true);
       sU.setLocationRelativeTo(this);
       sU.setVisible(true);
    }//GEN-LAST:event_txtUnidadMouseClicked

   
    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
      txtNombre.setText("");
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescripcionMouseClicked
        txtDescripcion.setText("");
    }//GEN-LAST:event_txtDescripcionMouseClicked

    private void txtCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoMouseClicked
      txtCodigo.setText("");
      NewCodigo nC = new NewCodigo(this, true);
      nC.setLocationRelativeTo(this);
      nC.setVisible(true);
    }//GEN-LAST:event_txtCodigoMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      
        try {
            String name = txtNombre.getText();
            String desc = txtDescripcion.getText();
            String code = txtCodigo.getText();
            String cantidad = spinCantidad.getValue().toString();
            String unidad = txtUnidad.getText();
            //------------------------------------------------------------------

            if (panel == false) {
                ModelProductos miProducto = new ModelProductos(code, name, desc, cantidad, unidad);
                controlProduct.insertProductMin(miProducto);
            }
//            //-------------------------------------------------------------------
//            else{
//                String cant_minima = spinMinima.getValue().toString();
//                String cant_maxima = spinMaxima.getValue().toString();
//                String fecha_vencimiento = txtFecha.getText() ;
//                String usuario_registra = txtRegistra.getText();
//
//                ModelProductos miProducto = new ModelProductos(code, name, desc, cantidad, cant_minima, cant_maxima, fecha_vencimiento, usuario_registra,fecha_vencimiento , unidad);
//                controlProduct.insertProductMax(miProducto);
//            }

            JOptionPane.showMessageDialog(this, "Genial! Has insertado el producto correctamente");
            this.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ups! Parece que hubo un error en los datos");

        }

        parent.restartInventario();

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddProduct dialog = new AddProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JSpinner spinCantidad;
    public static javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
